### PR TITLE
Update providers.json

### PR DESCRIPTION
**Pull request by 10by10pixel**
I made a fix to the upstream, so I'm just updating it here.

### CODE REVIEW

**Comment by ndaidong** [comment]
@10by10pixel thank you, your code has a little problem with coding style. Could you fix that?

**Comment by 10by10pixel** [comment]
@ndaidong It passed the CI code analysis. Can you clarify what you mean by code quality?

**Comment by ndaidong** [comment]
@10by10pixel I found that the CI didn't pass. The process is stopped after linting and does not touch on the test scripts yet. 
https://github.com/ndaidong/oembed-parser/pull/88/checks?check_run_id=1922804837

**Comment by 10by10pixel** [comment]
@ndaidong I fixed some bugs. CI tests are all passing now

**Comment by ndaidong** [comment]
@10by10pixel thank you, I will merge it now.

**Pull request merged**
